### PR TITLE
Modernize 'opennlp-addons' to be compatible with latest opennlp-tools release

### PR DESCRIPTION
**Pull request by mawiesne**
Change
-
- adjusts 'opennlp-addons' to be compatible with latest opennlp-tools release
- adjusts opennlp-tools to `2.2.0`
- adjusts parent project (org.apache.apache) to version `29`
- adjusts Java language level to `11`
- fixes compilation incompatibilities
- transforms existing JUnit tests towards JUnit 5.x
- updates morfologik dependency to version 2.1.9
- improves resource handling in some spots
- modernizes code style along the path
- adds GH actions config
- adjusts `.gitignore` to cover an additional IDE flavor
- improves JavaDoc along the path

### CODE REVIEW

**Comment by mawiesne** [comment]
@rzo1  I guess, your help is required with line endings transformation to cover Win users/environments...

**Comment by jzonthemtn** [comment]
Thanks @mawiesne!

**Review by kinow — APPROVED** [review]
+1, we just need to figure out what's wrong with the windows tests. Thanks @mawiesne !

**Comment by rzo1** [comment]
> @rzo1 I guess, your help is required with line endings transformation to cover Win users/environments...

https://github.com/apache/opennlp-addons/pull/13

**Review by rzo1 — APPROVED** [review]

**Comment by rzo1** [comment]
Great addition. Thanks.

**Pull request merged**
